#!/bin/bash
#
# ArceOS PXE 物理机部署脚本
# 用途：在真实物理机上配置PXE环境，接入现有网络
# 场景：服务器网卡 enOSp3s0，IP 192.168.1.2，物理开发板 IP 192.168.1.4
#

set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 日志函数
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# 显示帮助信息
show_help() {
    cat << EOF
用法: $0 [选项]

AxVisor PXE 物理机部署脚本（接入现有网络模式）

选项:
    -i, --install      安装并配置PXE环境
    -s, --start        启动PXE服务
    -t, --stop         停止PXE服务
    -c, --clean        清理PXE环境
    -h, --help         显示此帮助信息
    --status           显示PXE环境状态
    --interface NAME   指定网卡名称 (默认: enp3s0)
    --server-ip IP     指定服务器IP (默认: 192.168.1.2)
    --client-ip IP     指定客户端IP (默认: 192.168.1.4，仅用于 GRUB 内嵌配置)
    --kernel FILE      指定内核文件路径 (默认: ../arceos-helloworld)
    --mode MODE        DHCP模式: proxy|exclusive|none (默认: proxy)
                       - proxy: DHCP代理模式（推荐，不干扰现有DHCP）
                       - exclusive: 独占DHCP模式（会与现有DHCP冲突）
                       - none: 只提供TFTP服务（需配置现有DHCP的next-server）

示例:
    $0 --install                         # 使用默认配置安装
    $0 --install --mode proxy            # DHCP代理模式（推荐）
    $0 --status                          # 查看状态
    $0 --stop                            # 停止服务
    $0 --clean                           # 清理环境

EOF
    exit 0
}

# 检测系统信息
detect_system() {
    log_info "检测系统信息..."
    
    if [ ! -f /etc/os-release ]; then
        log_error "无法检测操作系统版本"
        exit 1
    fi
    
    . /etc/os-release
    OS_ID=${ID}
    OS_VERSION=${VERSION_ID}
    
    log_info "操作系统: ${PRETTY_NAME}"
    
    # 检查是否为root用户
    if [ "$EUID" -ne 0 ]; then
        log_error "请使用 root 权限运行此脚本"
        exit 1
    fi
}

# 检查网络接口
check_network_interface() {
    log_info "检查网络接口..."
    
    if ! ip link show "$INTERFACE" &> /dev/null; then
        log_error "网卡 $INTERFACE 不存在"
        log_info "可用的网卡列表:"
        ip link show | grep -E '^[0-9]+:' | awk '{print $2}' | tr -d ':'
        exit 1
    fi
    
    # 检查网卡是否有IP
    if ! ip addr show "$INTERFACE" | grep -q "inet "; then
        log_error "网卡 $INTERFACE 没有配置IP地址"
        exit 1
    fi
    
    # 获取实际的IP地址
    ACTUAL_IP=$(ip addr show "$INTERFACE" | grep "inet " | awk '{print $2}' | cut -d'/' -f1)
    
    if [ -n "$SERVER_IP" ] && [ "$ACTUAL_IP" != "$SERVER_IP" ]; then
        log_warn "网卡 $INTERFACE 的实际IP ($ACTUAL_IP) 与指定的IP ($SERVER_IP) 不一致"
        log_info "将使用实际IP: $ACTUAL_IP"
        SERVER_IP="$ACTUAL_IP"
    elif [ -z "$SERVER_IP" ]; then
        SERVER_IP="$ACTUAL_IP"
    fi
    
    log_success "网卡检查通过: $INTERFACE ($SERVER_IP)"
}

# 安装软件包
install_packages() {
    log_info "检查并安装必要的软件包..."
    
    # 安装 dnsmasq
    if ! command -v dnsmasq &> /dev/null; then
        log_info "安装 dnsmasq..."
        apt-get update -qq
        apt-get install -y dnsmasq
    fi
    
    # 安装网络工具
    if ! command -v ip &> /dev/null; then
        log_info "安装 iproute2..."
        apt-get install -y iproute2
    fi

    if ! command -v grub-mkimage &> /dev/null; then
        log_info "安装 grub EFI 工具..."
        apt-get install -y grub-efi-amd64-bin
    fi
    
    log_success "软件包检查完成"
}

# 配置dnsmasq - DHCP代理模式
configure_dnsmasq_proxy() {
    log_info "配置 dnsmasq (DHCP代理模式)..."
    
    # 停止可能正在运行的dnsmasq
    systemctl stop dnsmasq 2>/dev/null || true
    
    # 停止可能冲突的tftpd服务
    systemctl stop tftpd-hpa 2>/dev/null || true
    systemctl disable tftpd-hpa 2>/dev/null || true
    
    # 创建PXE配置文件 - DHCP代理模式
    cat > /etc/dnsmasq.d/pxe-physical.conf << EOF
# AxVisor PXE Configuration for Physical Board
# Generated by pxe-physical-deploy.sh on $(date)
# Mode: DHCP Proxy (不干扰现有DHCP服务器)

# 关闭本地 DNS 功能
port=0

# 监听物理网卡
interface=${INTERFACE}
bind-interfaces

# DHCP代理模式 - 正确的语法
# 只响应PXE客户端，不分配IP（IP由现有DHCP分配）
dhcp-range=192.168.1.0,proxy

# PXE 启动配置
dhcp-boot=undionly.kpxe
pxe-service=x86PC, "iPXE", boot.ipxe

# TFTP 配置
enable-tftp
tftp-root=/var/lib/tftpboot

# 日志（用于调试）
log-dhcp
log-queries
EOF
    
    # 确保主配置文件包含子配置目录
    if ! grep -q "^conf-dir=/etc/dnsmasq.d" /etc/dnsmasq.conf; then
        echo "conf-dir=/etc/dnsmasq.d/,*.conf" >> /etc/dnsmasq.conf
    fi
    
    log_success "dnsmasq 配置完成 (DHCP代理模式)"
}

# 配置dnsmasq - 独占DHCP模式
configure_dnsmasq_exclusive() {
    log_warn "警告：独占DHCP模式会与现有DHCP服务器冲突！"
    log_warn "建议使用 --mode proxy 模式"
    sleep 2
    
    # 停止可能正在运行的dnsmasq
    systemctl stop dnsmasq 2>/dev/null || true
    systemctl stop tftpd-hpa 2>/dev/null || true
    systemctl disable tftpd-hpa 2>/dev/null || true
    
    # 计算192.168.1.0/24网段的DHCP范围
    local base_ip=$(echo $SERVER_IP | cut -d'.' -f1-3)
    local dhcp_start="${base_ip}.200"
    local dhcp_end="${base_ip}.250"
    
    cat > /etc/dnsmasq.d/pxe-physical.conf << EOF
# AxVisor PXE Configuration for Physical Board
# Mode: Exclusive DHCP (会与现有DHCP冲突)

# 关闭本地 DNS 功能
port=0

# 监听物理网卡
interface=${INTERFACE}
bind-interfaces

# 独占DHCP模式
dhcp-range=${dhcp_start},${dhcp_end},12h
dhcp-option=3,${base_ip}.1            # 默认网关
dhcp-option=6,8.8.8.8                 # DNS 服务器

# PXE 启动配置
dhcp-boot=undionly.kpxe
pxe-service=x86PC, "iPXE", boot.ipxe

# TFTP 配置
enable-tftp
tftp-root=/var/lib/tftpboot

log-dhcp
EOF
    
    log_success "dnsmasq 配置完成 (独占DHCP模式)"
}

# 配置dnsmasq - 仅TFTP模式
configure_dnsmasq_tftp_only() {
    log_info "配置 dnsmasq (仅TFTP模式)..."
    log_warn "注意：此模式需要配置现有DHCP服务器的 next-server 选项指向 $SERVER_IP"
    
    systemctl stop dnsmasq 2>/dev/null || true
    systemctl stop tftpd-hpa 2>/dev/null || true
    systemctl disable tftpd-hpa 2>/dev/null || true
    
    cat > /etc/dnsmasq.d/pxe-physical.conf << EOF
# AxVisor PXE Configuration for Physical Board
# Mode: TFTP Only (需要配置现有DHCP的next-server)

# 关闭本地 DNS 和 DHCP 功能
port=0
no-dhcp-interface=${INTERFACE}

# TFTP 配置
enable-tftp
tftp-root=/var/lib/tftpboot
tftp-no-fail

log-dhcp
EOF
    
    log_success "dnsmasq 配置完成 (仅TFTP模式)"
    log_info "请在现有DHCP服务器上配置:"
    log_info "  next-server = $SERVER_IP"
    log_info "  bootfile = undionly.kpxe"
}

# 准备TFTP目录
prepare_tftp_directory() {
    log_info "准备 TFTP 目录..."
    
    # 创建TFTP根目录
    mkdir -p /var/lib/tftpboot
    chmod -R 777 /var/lib/tftpboot
    
    # 下载 iPXE 镜像（如果不存在）
    if [ ! -f /var/lib/tftpboot/undionly.kpxe ]; then
        log_info "下载 iPXE 镜像..."
        wget -q --timeout=30 -O /var/lib/tftpboot/undionly.kpxe https://boot.ipxe.org/undionly.kpxe || {
            log_error "下载 iPXE 镜像失败，请检查网络连接"
            exit 1
        }
    fi
    
    # 复制内核文件
    if [ -f "$KERNEL_FILE" ]; then
        log_info "复制内核文件: $KERNEL_FILE"
        cp -f "$KERNEL_FILE" /var/lib/tftpboot/kernel
    else
        log_error "内核文件不存在: $KERNEL_FILE"
        log_info "请确保内核文件存在，或使用 --kernel 参数指定路径"
        exit 1
    fi
    
    # 生成带内嵌网络配置的 GRUB EFI 镜像
    cat > /tmp/grub-embedded.cfg << EOF
serial --unit=0 --speed=115200
terminal_input console serial
terminal_output console serial

net_bootp
set net_default_ip=${CLIENT_IP}
set net_default_server=${SERVER_IP}

multiboot (tftp,${SERVER_IP})/kernel
boot
EOF

    grub-mkimage -o /var/lib/tftpboot/grubx64.efi -O x86_64-efi \
        -p "" \
        -c /tmp/grub-embedded.cfg \
        normal tftp net boot multiboot multiboot2 \
        efinet linux linux16 serial terminal \
        echo cat ls test

    rm -f /tmp/grub-embedded.cfg

    # 创建 iPXE 启动脚本
    cat > /var/lib/tftpboot/boot.ipxe << EOF
#!ipxe
echo ===================================
echo   ArceOS Boot via GRUB
echo ===================================
echo Loading GRUB EFI bootloader...
chain tftp://${SERVER_IP}/grubx64.efi
EOF
    
    chmod -R 755 /var/lib/tftpboot
    
    log_success "TFTP 目录准备完成"
    
    # 显示文件列表
    log_info "TFTP 文件列表:"
    ls -lh /var/lib/tftpboot/
}

# 启动PXE服务
start_pxe_service() {
    log_info "启动 PXE 服务..."
    
    # 测试配置
    if ! dnsmasq --test &> /dev/null; then
        log_error "dnsmasq 配置文件有误"
        dnsmasq --test
        exit 1
    fi
    
    # 启动 dnsmasq
    systemctl start dnsmasq
    systemctl enable dnsmasq
    
    # 检查服务状态
    if systemctl is-active --quiet dnsmasq; then
        log_success "PXE 服务启动成功"
    else
        log_error "PXE 服务启动失败"
        journalctl -u dnsmasq -n 30 --no-pager
        exit 1
    fi
    
    # 显示监听端口
    log_info "服务端口状态:"
    netstat -tuln | grep -E ':(67|69|4011)\s' || true
    
    # 显示配置摘要
    log_info "配置摘要:"
    echo "  网卡接口: $INTERFACE"
    echo "  服务器IP: $SERVER_IP"
    echo "  客户端IP: $CLIENT_IP"
    echo "  DHCP模式: $DHCP_MODE"
    echo "  内核文件: $KERNEL_FILE"
}

# 停止PXE服务
stop_pxe_service() {
    log_info "停止 PXE 服务..."
    
    systemctl stop dnsmasq 2>/dev/null || true
    log_success "PXE 服务已停止"
}

# 清理环境
clean_environment() {
    log_info "清理 PXE 环境..."
    
    # 停止服务
    systemctl stop dnsmasq 2>/dev/null || true
    
    # 删除配置文件
    rm -f /etc/dnsmasq.d/pxe-physical.conf
    
    # 询问是否删除TFTP文件
    read -p "是否删除 TFTP 目录 (/var/lib/tftpboot)? [y/N]: " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -rf /var/lib/tftpboot
        log_info "TFTP 目录已删除"
    else
        log_info "保留 TFTP 目录"
    fi
    
    log_success "环境清理完成"
}

# 显示状态
show_status() {
    log_info "PXE 环境状态:"
    echo "================================"
    
    # 检查网卡
    if ip link show "$INTERFACE" &> /dev/null; then
        local ip_addr=$(ip addr show "$INTERFACE" | grep "inet " | awk '{print $2}')
        local link_state=$(ip link show "$INTERFACE" | grep -o 'state [A-Z]*' | awk '{print $2}')
        echo -e "${GREEN}✓${NC} 网卡 $INTERFACE: $ip_addr ($link_state)"
    else
        echo -e "${RED}✗${NC} 网卡 $INTERFACE 不存在"
    fi
    
    # 检查dnsmasq服务
    if systemctl is-active --quiet dnsmasq; then
        echo -e "${GREEN}✓${NC} dnsmasq 服务: 运行中"
        
        # 显示DHCP模式
        if grep -q "dhcp-range=.*proxy" /etc/dnsmasq.d/pxe-physical.conf 2>/dev/null; then
            echo "   DHCP模式: 代理模式"
        elif grep -q "no-dhcp-interface" /etc/dnsmasq.d/pxe-physical.conf 2>/dev/null; then
            echo "   DHCP模式: 仅TFTP"
        else
            echo "   DHCP模式: 独占DHCP"
        fi
    else
        echo -e "${RED}✗${NC} dnsmasq 服务: 未运行"
    fi
    
    # 检查TFTP文件
    echo -e "\nTFTP 文件:"
    for file in undionly.kpxe boot.ipxe grubx64.efi kernel; do
        if [ -f "/var/lib/tftpboot/$file" ]; then
            size=$(ls -lh "/var/lib/tftpboot/$file" | awk '{print $5}')
            echo -e "${GREEN}✓${NC} $file ($size)"
        else
            echo -e "${RED}✗${NC} $file (缺失)"
        fi
    done
    
    # 检查端口
    echo -e "\n监听端口:"
    if netstat -tuln | grep -q ':67\s'; then
        echo -e "${GREEN}✓${NC} DHCP 端口 (67/udp)"
    else
        echo -e "${YELLOW}○${NC} DHCP 端口 (67/udp) - 未监听（可能使用代理模式）"
    fi
    
    if netstat -tuln | grep -q ':69\s'; then
        echo -e "${GREEN}✓${NC} TFTP 端口 (69/udp)"
    else
        echo -e "${RED}✗${NC} TFTP 端口 (69/udp)"
    fi
    
    # 显示配置文件
    if [ -f /etc/dnsmasq.d/pxe-physical.conf ]; then
        echo -e "\n配置文件: /etc/dnsmasq.d/pxe-physical.conf"
        echo "----------------------------------------"
        grep -v "^#" /etc/dnsmasq.d/pxe-physical.conf | grep -v "^$" | head -10
        echo "----------------------------------------"
    fi
    
    echo "================================"
}

# 主函数
main() {
    # 默认参数
    INTERFACE="enp3s0"
    SERVER_IP="192.168.1.2"
    CLIENT_IP="192.168.1.4"
    KERNEL_FILE="../arceos-helloworld"
    DHCP_MODE="proxy"
    ACTION=""
    
    # 解析命令行参数
    while [[ $# -gt 0 ]]; do
        case $1 in
            -i|--install)
                ACTION="install"
                shift
                ;;
            -s|--start)
                ACTION="start"
                shift
                ;;
            -t|--stop)
                ACTION="stop"
                shift
                ;;
            -c|--clean)
                ACTION="clean"
                shift
                ;;
            --status)
                ACTION="status"
                shift
                ;;
            --interface)
                INTERFACE="$2"
                shift 2
                ;;
            --server-ip)
                SERVER_IP="$2"
                shift 2
                ;;
            --client-ip)
                CLIENT_IP="$2"
                shift 2
                ;;
            --kernel)
                KERNEL_FILE="$2"
                shift 2
                ;;
            --mode)
                DHCP_MODE="$2"
                shift 2
                ;;
            -h|--help)
                show_help
                ;;
            *)
                log_error "未知选项: $1"
                show_help
                ;;
        esac
    done
    
    # 如果没有指定操作，显示帮助
    if [ -z "$ACTION" ]; then
        show_help
    fi
    
    # 显示横幅
    cat << 'EOF'
    ___   ____  __  __________    __      _____  _
   /   | / __ \/  |/  / ____/ /   / /     |  __ \| |
  / /| |/ / / / /|_/ / __  / /   / /      | |__) | | _____  ___   _ _ __
 / ___ / /_/ / /  / / /_/ / /___/ /___    |  ___/| |/ _ \ \/ / | | | '_ \
/_/  |_\____/_/  /_/\____/_____/_____/    |_|    |_|\___/>_/\_\_|_|_| |_|

AxVisor PXE 物理机部署工具 (接入现有网络)

EOF
    
    # 执行相应的操作
    case $ACTION in
        install)
            detect_system
            install_packages
            check_network_interface
            
            # 根据DHCP模式配置dnsmasq
            case $DHCP_MODE in
                proxy)
                    configure_dnsmasq_proxy
                    ;;
                exclusive)
                    configure_dnsmasq_exclusive
                    ;;
                none)
                    configure_dnsmasq_tftp_only
                    ;;
                *)
                    log_error "未知的DHCP模式: $DHCP_MODE"
                    log_info "支持的模式: proxy, exclusive, none"
                    exit 1
                    ;;
            esac
            
            prepare_tftp_directory
            start_pxe_service
            
            log_success "PXE 环境部署完成！"
            log_info ""
            log_info "下一步操作:"
            log_info "1. 确认物理开发板已连接网线"
            log_info "2. 开发板BIOS已启用 Network Boot / PXE Boot"
            log_info "3. 重启开发板，观察PXE启动过程"
            log_info "4. 使用 '$0 --status' 查看服务状态"
            log_info ""
            log_warn "注意：如果使用 proxy 模式，PXE启动可能需要10-30秒"
            ;;
        start)
            check_network_interface
            start_pxe_service
            ;;
        stop)
            stop_pxe_service
            ;;
        clean)
            clean_environment
            ;;
        status)
            show_status
            ;;
    esac
}

# 执行主函数
main "$@"
